### ISSUE TITLE
Common goal?

### ISSUE THREAD

**Issue by pauldijou** [elm-node/core#3]
Hi folks,

A friend of mine just show me your repo. Nice work here. As a matter of fact, I'm already working on supporting the full Node API in Elm. Here is my work in progress so far [pauldijou/elm-node](https://github.com/pauldijou/elm-node).

I just wanted to start talking if you would like to share efforts one way or another since it looks like we are aiming for the same goal.

Cheers

**Comment by alexgig** [comment]
Thanks for reaching out Paul. Lets continue talking on Slack.
